# Configuration for devevelopment environments: unless you are a Tobira
# developer, you are not intersted in this file.

[db]
user = "tobira"
password = "tobira"
host = "127.0.0.1"

[assets]
logo.large = "logo-large.svg"
logo.small = "logo-small.svg"

[log]
level = "trace"

[opencast]
host = "localhost:8080"
use_insecure_connection = true
sync_user = "admin"
sync_password = "opencast"
